name: Test

on:
    push:
        branches: [ master ]
    schedule:
        - cron: '0 0 */10 * *'

env:
    LLVM_VERSION: 11
    GCC_VERSION: 11

jobs:
    clang:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install pyyaml
              run: pip install pyyaml
            - uses: actions/cache@v1
              id: cache-clang
              with:
                  path: /var/cache/apt/archives
                  key: clang-cache-${{ github.sha }}
            - name: Download Clang
              if: steps.cache-clang.outputs.cache-hit != 'true'
              run: |
                  REPO_NAME='deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
                  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
                  sudo add-apt-repository "$REPO_NAME"
                  sudo apt-get update
                  sudo apt-get install --download-only -y clang-$LLVM_VERSION libc++-$LLVM_VERSION-dev
            - name: Install Clang
              run: |
                  sudo apt-get install -y clang-$LLVM_VERSION libc++-$LLVM_VERSION-dev
                  mkdir bin
                  cp -s /usr/bin/clang-$LLVM_VERSION bin/clang
                  echo "::set-env name=PATH::$PWD/bin:$PATH"

            - name: Test attributes
              run: |
                  python3.8 tools/do_test.py clang attributes --verbose

            - name: Test language
              run: |
                  python3.8 tools/do_test.py clang language --verbose

            - name: Test library
              run: |
                  python3.8 tools/do_test.py clang library --verbose \
                    --extra-args -stdlib=libc++

    gcc:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install pyyaml
              run: pip install pyyaml
            - uses: actions/cache@v1
              id: cache-gcc
              with:
                  path: gcc-latest
                  key: gcc-cache-${{ github.sha }}
                  restore-keys: gcc-cache-
            - name: Install GCC
              run: |
                  LOC="$PWD"
                  mkdir gcc && cd gcc
                  URL="https://gcc.gnu.org/pub/gcc/snapshots/LATEST-$GCC_VERSION"
                  wget "$URL/index.html"
                  TARFILE=$(grep -Eo "gcc-$GCC_VERSION-[0-9]{8}.tar.xz" index.html | uniq)
                  PKGDATE=$(echo $TARFILE | grep -Eo "[0-9]{8}")
                  BASENAME=gcc-$GCC_VERSION-$PKGDATE
                  if "$LOC/gcc-latest/bin/gcc" --version | grep $PKGDATE; then
                      :
                  else
                      sudo apt-get install -y flex
                      wget "$URL/$TARFILE"
                      tar -xf "$TARFILE"
                      cd $BASENAME
                      ./contrib/download_prerequisites
                      mkdir objdir && cd objdir
                      ../configure --prefix="$LOC/gcc-latest" \
                        --enable-languages=c,c++ --disable-bootstrap --disable-multilib \
                        --without-isl
                      make -j2 && make install
                  fi
                  echo "::set-env name=PATH::$LOC/gcc-latest/bin:$PATH"

            - name: Test attributes
              run: |
                  python3.8 tools/do_test.py gcc attributes --verbose

            - name: Test language
              run: |
                  python3.8 tools/do_test.py gcc language --verbose

            - name: Test library
              run: |
                  python3.8 tools/do_test.py gcc library --verbose

            - uses: actions/cache@v1
              id: cache-clang
              with:
                  path: /var/cache/apt/archives
                  key: clang-cache-${{ github.sha }}
            - name: Download Clang
              if: steps.cache-clang.outputs.cache-hit != 'true'
              run: |
                  REPO_NAME='deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
                  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
                  sudo add-apt-repository "$REPO_NAME"
                  sudo apt-get update
                  sudo apt-get install --download-only -y clang-$LLVM_VERSION libc++-$LLVM_VERSION-dev
            - name: Install Clang
              run: |
                  sudo apt-get install -y clang-$LLVM_VERSION
                  mkdir bin
                  cp -s /usr/bin/clang-$LLVM_VERSION bin/clang
                  echo "::set-env name=PATH::$PWD/bin:$PATH"

            - name: Test library with Clang
              run: |
                  python3.8 tools/do_test.py gcc library --verbose \
                    --cc clang \
                    --extra-args -fno-caret-diagnostics -stdlib=libstdc++
